run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
