package agent

import (
	"strings"
	"testing"
)

func TestExtractModelShortName(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{name: "empty", input: "", want: ""},
		{name: "bare model", input: "claude-opus-4-6", want: "claude-opus-4-6"},
		{name: "provider/model", input: "github-copilot/claude-opus-4.8", want: "claude-opus-4.8"},
		{name: "provider/model@variant", input: "google-vertex-anthropic/claude-opus-4-6@default", want: "claude-opus-4-6"},
		{name: "model@variant only", input: "claude-opus-4-6@default", want: "claude-opus-4-6"},
		{name: "nested provider", input: "a/b/claude-sonnet-4@fast", want: "claude-sonnet-4"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ExtractModelShortName(tt.input)
			if got != tt.want {
				t.Errorf("ExtractModelShortName(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestBotComment(t *testing.T) {
	t.Run("without version", func(t *testing.T) {
		a := &Agent{cfg: Config{}}
		got := a.botComment()
		if !strings.Contains(got, "Generated by [oompa]") {
			t.Errorf("expected visible attribution, got: %q", got)
		}
		if !strings.Contains(got, "<!-- oompa-bot -->") {
			t.Errorf("expected invisible marker, got: %q", got)
		}
		if !strings.HasPrefix(got, "---\n") {
			t.Errorf("expected horizontal rule prefix, got: %q", got)
		}
	})

	t.Run("with version", func(t *testing.T) {
		a := &Agent{cfg: Config{Version: "abc123def456"}}
		got := a.botComment()
		if !strings.Contains(got, "Generated by [oompa]") {
			t.Errorf("expected visible attribution, got: %q", got)
		}
		if !strings.Contains(got, "<!-- oompa-bot v:abc123d -->") {
			t.Errorf("expected versioned marker, got: %q", got)
		}
	})

	t.Run("contains botMarker prefix", func(t *testing.T) {
		a := &Agent{cfg: Config{}}
		got := a.botComment()
		if !strings.Contains(got, botMarker) {
			t.Errorf("botComment() must contain botMarker prefix %q for detection, got: %q", botMarker, got)
		}
	})
}

func TestDefaultAssistedBy(t *testing.T) {
	tests := []struct {
		name    string
		backend string
		model   string
		want    string
	}{
		{name: "empty backend", backend: "", model: "", want: ""},
		{name: "backend only", backend: "claudecode", model: "", want: "oompa <https://github.com/qinqon/oompa>"},
		{name: "with model", backend: "opencode", model: "google-vertex-anthropic/claude-opus-4-6@default", want: "oompa with claude-opus-4-6 <https://github.com/qinqon/oompa>"},
		{name: "simple model", backend: "claudecode", model: "claude-opus-4-6", want: "oompa with claude-opus-4-6 <https://github.com/qinqon/oompa>"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := DefaultAssistedBy(tt.backend, tt.model)
			if got != tt.want {
				t.Errorf("DefaultAssistedBy(%q, %q) = %q, want %q", tt.backend, tt.model, got, tt.want)
			}
		})
	}
}
