package agent

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"time"
)

const (
	// botMarker is a hidden HTML comment used to detect agent-posted comments.
	// Used for filtering (strings.Contains checks). The versioned marker
	// is generated by Agent.botComment() for output.
	botMarker = "<!-- oompa-bot"

	// Status values for IssueWork
	StatusImplementing = "implementing"
	StatusPROpen       = "pr-open"
	StatusFailed       = "failed"

	// Labels
	labelAIFailed = "ai-failed"
)

func ciMarker(sha, checkName string) string {
	return fmt.Sprintf("<!-- oompa-bot ci:%s:%s -->", shortSHA(sha), checkName)
}

// issueBranchName returns the branch name for a given issue number.
func issueBranchName(issueNumber int) string {
	return fmt.Sprintf("ai/issue-%d", issueNumber)
}

// classifyPRs finds the first open PR and checks if any PR was merged.
func classifyPRs(prs []PR) (openPR *PR, hasMerged bool) {
	for i := range prs {
		if prs[i].State == "open" && openPR == nil {
			openPR = &prs[i]
		}
		if prs[i].Merged {
			hasMerged = true
		}
		if openPR != nil && hasMerged {
			break
		}
	}
	return openPR, hasMerged
}

// Agent holds all dependencies and runs the main processing loop.
type Agent struct {
	gh        GitHubClient
	runner    CommandRunner
	worktrees WorktreeManager
	state     *State
	cfg       Config
	logger    *slog.Logger
	tokenFunc func(context.Context) (string, error) // optional: provides fresh GitHub tokens (for App auth)
	codeAgent CodeAgent                             // coding agent backend (Claude Code or OpenCode)
	emitter   EventEmitter                          // optional: event emitter for observability (default: NoopEmitter)
}

// botComment returns the bot marker with the agent version embedded.
// The marker starts with "<!-- oompa-bot" so botMarker detection still works.
func (a *Agent) botComment() string {
	if a.cfg.Version != "" {
		return fmt.Sprintf("<!-- oompa-bot v:%s -->", shortSHA(a.cfg.Version))
	}
	return "<!-- oompa-bot -->"
}

// SetTokenFunc sets a function that provides fresh GitHub tokens.
// Used with GitHub App authentication where installation tokens expire after ~1 hour.
func (a *Agent) SetTokenFunc(fn func(context.Context) (string, error)) {
	a.tokenFunc = fn
}

// RefreshToken updates the GitHub token if a token function is set.
// Call this before each poll cycle to ensure the token is fresh.
func (a *Agent) RefreshToken(ctx context.Context) error {
	if a.tokenFunc == nil {
		return nil
	}
	token, err := a.tokenFunc(ctx)
	if err != nil {
		return fmt.Errorf("refreshing GitHub token: %w", err)
	}
	a.cfg.GitHubToken = token
	os.Setenv("GH_TOKEN", token)

	// Update the runner's GH_TOKEN environment variable
	if execRunner, ok := a.runner.(*ExecRunner); ok {
		execRunner.SetGHToken(token)
	}

	return nil
}

// runSequential executes a function on each item sequentially.
// Each role entry runs within its own goroutine, so no worker pool is needed.
// Stops early if the context is cancelled (e.g. during graceful shutdown).
func runSequential[T any](ctx context.Context, items []T, fn func(context.Context, T)) {
	for _, item := range items {
		if ctx.Err() != nil {
			return
		}
		fn(ctx, item)
	}
}

// Task structs for parallel execution

type newIssueTask struct {
	issue        Issue
	branchName   string
	worktreePath string
	work         *IssueWork
}

type reviewTask struct {
	work          *IssueWork
	humanComments []ReviewComment
	humanReviews  []PRReview
	maxCommentID  int64 // max ID across ALL fetched comments (including filtered ones)
	maxReviewID   int64 // max ID across ALL fetched reviews (including filtered ones)
}

type ciTask struct {
	work     *IssueWork
	headSHA  string
	failures []CheckRun
	diff     string
	commits  []Commit
}

type conflictTask struct {
	work         *IssueWork
	headSHA      string
	rebaseErr    error
	rebaseStderr string
}

// NewAgent creates a new Agent with all dependencies wired.
func NewAgent(gh GitHubClient, runner CommandRunner, worktrees WorktreeManager, state *State, cfg Config, logger *slog.Logger, codeAgent CodeAgent) *Agent {
	return &Agent{
		gh:        gh,
		runner:    runner,
		worktrees: worktrees,
		state:     state,
		cfg:       cfg,
		logger:    logger,
		codeAgent: codeAgent,
		emitter:   &NoopEmitter{},
	}
}

// SetEmitter sets the event emitter for observability.
// If not called, a NoopEmitter is used (zero overhead).
// Passing nil is ignored to prevent panics.
func (a *Agent) SetEmitter(emitter EventEmitter) {
	if emitter == nil {
		return
	}
	a.emitter = emitter
}

// emit is a convenience method to emit an event with the current timestamp.
// The nil guard exists because tests may construct Agent via struct literals
// without using NewAgent, leaving emitter uninitialized.
func (a *Agent) emit(event Event) {
	if a.emitter == nil {
		return
	}
	if event.Timestamp.IsZero() {
		event.Timestamp = time.Now()
	}
	a.emitter.Emit(event)
}

// workerName returns the worker identifier for event emission.
// Uses the config's Owner/Repo as the base, with an optional :Role suffix.
func (a *Agent) workerName() string {
	name := a.cfg.Owner + "/" + a.cfg.Repo
	if a.cfg.Role != "" {
		name += ":" + a.cfg.Role
	}
	return name
}

// EmitPollCycleStart emits a poll cycle start event.
func (a *Agent) EmitPollCycleStart() {
	a.emit(Event{
		Type:     EventPollCycleStart,
		Category: CategoryPollCycle,
		Worker:   a.workerName(),
		State:    "working",
		Action:   "Poll cycle started",
	})
}

// EmitPollCycleEnd emits a poll cycle end event.
func (a *Agent) EmitPollCycleEnd() {
	a.emit(Event{
		Type:     EventPollCycleEnd,
		Category: CategoryPollCycle,
		Worker:   a.workerName(),
		State:    "idle",
		Action:   "Poll cycle completed",
	})
}

// CleanupDone removes worktrees for merged or closed PRs.
func (a *Agent) CleanupDone(ctx context.Context) {
	a.emit(Event{
		Type:     EventActionStarted,
		Category: CategoryCleanup,
		Worker:   a.workerName(),
		Action:   "Cleaning up merged/closed PRs",
	})
	defer a.emit(Event{
		Type:     EventActionCompleted,
		Category: CategoryCleanup,
		Worker:   a.workerName(),
		State:    "idle",
		Action:   "Cleanup complete",
	})
	for key, work := range a.state.ActiveIssues {
		if work.PRNumber == 0 {
			continue
		}

		state, err := a.gh.GetPRState(ctx, a.cfg.Owner, a.cfg.Repo, work.PRNumber)
		if err != nil {
			a.logger.Error("failed to get PR state", "pr", work.PRNumber, "error", err)
			continue
		}

		if state != "merged" && state != "closed" {
			continue
		}

		a.logger.Info("cleaning up done PR", "pr", work.PRNumber, "state", state)

		if err := a.worktrees.RemoveWorktree(ctx, work.WorktreePath); err != nil {
			a.logger.Error("failed to remove worktree", "path", work.WorktreePath, "error", err)
		}

		delete(a.state.ActiveIssues, key)
	}
}

// HasWatchedPRs returns true if the agent is configured to watch specific PRs.
func (a *Agent) HasWatchedPRs() bool {
	return len(a.cfg.WatchPRs) > 0
}

// ShouldRunReaction returns true if the given reaction type should be executed.
// If cfg.Reactions is empty, all reactions are enabled.
// Valid reaction names: "reviews", "ci", "conflicts", "rebase".
func (a *Agent) ShouldRunReaction(reaction string) bool {
	if len(a.cfg.Reactions) == 0 {
		return true
	}
	return slices.Contains(a.cfg.Reactions, reaction)
}

// ShouldSkipComment returns true if the given comment category should be suppressed.
// When a category is skipped, oompa still performs the underlying work but does not
// post the human-visible GitHub comment. Deduplication marker comments are never skipped.
// Valid categories: "ci-unrelated", "ci-infrastructure", "ci-related", "conflict", "rebase", "flaky", "issue-in-progress".
func (a *Agent) ShouldSkipComment(category string) bool {
	return slices.Contains(a.cfg.SkipComments, category)
}

// BootstrapWatchedPRs creates IssueWork entries for directly-specified PR numbers.
// Called each poll cycle to ensure watched PRs are tracked in state.
func (a *Agent) BootstrapWatchedPRs(ctx context.Context) {
	for _, prNumber := range a.cfg.WatchPRs {
		// Check if already tracked by any key
		alreadyTracked := false
		for _, work := range a.state.ActiveIssues {
			if work.PRNumber == prNumber {
				alreadyTracked = true
				break
			}
		}
		if alreadyTracked {
			continue
		}

		pr, err := a.gh.GetPR(ctx, a.cfg.Owner, a.cfg.Repo, prNumber)
		if err != nil {
			a.logger.Error("failed to get watched PR details", "pr", prNumber, "error", err)
			continue
		}

		if pr.Merged || pr.State == "closed" {
			a.logger.Info("skipping watched PR (already closed/merged)", "pr", prNumber, "state", pr.State)
			continue
		}

		branchName := pr.Head
		worktreePath := filepath.Join(a.cfg.CloneDir, "worktrees", branchName)

		work := &IssueWork{
			IssueTitle:   pr.Title,
			WorktreePath: worktreePath,
			BranchName:   branchName,
			PRNumber:     prNumber,
			Status:       "pr-open",
			CreatedAt:    time.Now(),
		}

		a.state.ActiveIssues[IssueKey(a.cfg.Owner, a.cfg.Repo, prNumber)] = work
		a.logger.Info("bootstrapped watched PR", "pr", prNumber, "branch", branchName, "title", pr.Title)
	}
}

// hasExistingBotComment returns true if a bot comment containing the given text
// already exists on the issue.
func (a *Agent) hasExistingBotComment(ctx context.Context, issueNumber int, text string) bool {
	comments, err := a.gh.GetIssueComments(ctx, a.cfg.Owner, a.cfg.Repo, issueNumber, 0)
	if err != nil {
		return false
	}
	for _, c := range comments {
		if strings.Contains(c.Body, botMarker) && strings.Contains(c.Body, text) {
			return true
		}
	}
	return false
}

// parseFlakyMatch parses Claude's response to a flaky match prompt.
// Returns the matched issue number and true if the response is "MATCH <number>".
func parseFlakyMatch(response string) (int, bool) {
	response = strings.TrimLeft(response, "*_")
	response = strings.TrimSpace(response)
	if !strings.HasPrefix(response, "MATCH") {
		return 0, false
	}
	numStr := strings.TrimSpace(strings.TrimPrefix(response, "MATCH"))
	numStr = strings.TrimPrefix(numStr, "#")
	n, err := strconv.Atoi(numStr)
	if err != nil || n <= 0 {
		return 0, false
	}
	return n, true
}

// parseFailingTest extracts the failing test name from an UNRELATED explanation.
// It looks for a line starting with "FAILING_TEST:" and returns the trimmed value.
// Returns empty string if no FAILING_TEST line is found.
func parseFailingTest(explanation string) string {
	for line := range strings.SplitSeq(explanation, "\n") {
		line = strings.TrimSpace(line)
		if after, ok := strings.CutPrefix(line, "FAILING_TEST:"); ok {
			return strings.TrimSpace(after)
		}
	}
	return ""
}

// shortSHA returns the first 7 characters of a SHA, or the full string if shorter.
func shortSHA(sha string) string {
	if len(sha) > 7 {
		return sha[:7]
	}
	return sha
}

func (a *Agent) alreadyCheckedCI(ctx context.Context, prNumber int, sha, checkName string) bool {
	// Check in-memory state first (used when comments are skipped)
	key := sha + ":" + checkName
	for _, work := range a.state.ActiveIssues {
		if work.PRNumber == prNumber && work.CheckedCIChecks[key] {
			return true
		}
	}

	// Fall back to checking comment markers (used when comments are posted)
	comments, err := a.gh.GetIssueComments(ctx, a.cfg.Owner, a.cfg.Repo, prNumber, 0)
	if err != nil {
		return false
	}
	marker := ciMarker(sha, checkName)
	for _, c := range comments {
		if strings.Contains(c.Body, marker) {
			return true
		}
	}
	return false
}

// markCIChecked records that a CI check has been investigated for dedup purposes.
func (a *Agent) markCIChecked(work *IssueWork, sha, checkName string) {
	if work.CheckedCIChecks == nil {
		work.CheckedCIChecks = make(map[string]bool)
	}
	work.CheckedCIChecks[sha+":"+checkName] = true
}

// originDefaultBranch returns "origin/<default-branch>" (e.g. "origin/main", "origin/master").
func (a *Agent) originDefaultBranch() string {
	if wtm, ok := a.worktrees.(*GitWorktreeManager); ok {
		return wtm.OriginDefaultBranch()
	}
	return "origin/main"
}

// defaultBranch returns the default branch name (e.g. "main", "master").
func (a *Agent) defaultBranch() string {
	if wtm, ok := a.worktrees.(*GitWorktreeManager); ok {
		return wtm.DefaultBranch()
	}
	return "main"
}

// pushRemote returns the name of the push remote (e.g. "origin", "fork").
func (a *Agent) pushRemote() string {
	if wtm, ok := a.worktrees.(*GitWorktreeManager); ok {
		return wtm.PushRemote()
	}
	return "origin"
}

// issueAssignedTo returns true if the given user is among the issue's assignees.
func issueAssignedTo(issue Issue, user string) bool {
	return slices.Contains(issue.Assignees, user)
}

// isAllowedReviewer returns true if the user is in the reviewers whitelist.
// If the whitelist is empty, all users are allowed.
func (a *Agent) isAllowedReviewer(user string) bool {
	if len(a.cfg.Reviewers) == 0 {
		return true
	}
	return slices.Contains(a.cfg.Reviewers, user)
}

// truncateString returns the first maxLen characters of s, with "..." appended if truncated.
func truncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}

// isConflictError returns true if the stderr from a git rebase contains conflict indicators.
func isConflictError(stderr string) bool {
	lowerStderr := strings.ToLower(stderr)
	return strings.Contains(lowerStderr, "conflict") || strings.Contains(lowerStderr, "could not apply")
}

// isUnstagedChangesError returns true if the stderr from a git rebase indicates
// unstaged changes are blocking the rebase (e.g. upstream file deletions).
func isUnstagedChangesError(stderr string) bool {
	return strings.Contains(strings.ToLower(stderr), "unstaged changes")
}

// markIssueFailed marks an issue as failed, unassigns the agent, and adds the ai-failed label.
func (a *Agent) markIssueFailed(ctx context.Context, issueNumber int, work *IssueWork) {
	work.Status = StatusFailed
	if err := a.gh.UnassignIssue(ctx, a.cfg.Owner, a.cfg.Repo, issueNumber, a.cfg.GitHubUser); err != nil {
		a.logger.Warn("failed to unassign issue", "issue", issueNumber, "error", err)
	}
	if err := a.gh.AddLabel(ctx, a.cfg.Owner, a.cfg.Repo, issueNumber, labelAIFailed); err != nil {
		a.logger.Warn("failed to add failure label", "issue", issueNumber, "error", err)
	}
}
