package agent

import "fmt"

// Hidden HTML-comment markers embedded in bot-posted GitHub comments. They
// make agent output machine-recognizable across restarts: every marker
// starts with botMarker so a single prefix check identifies bot comments,
// and the suffix encodes what was handled so reactions can deduplicate
// (skip a CI failure or rebase attempt already commented on).
const botMarker = "<!-- oompa-bot"

// ciMarker tags a CI investigation comment for one commit and check, so the
// same failure is not re-investigated.
func ciMarker(sha, checkName string) string {
	return fmt.Sprintf("%s ci:%s:%s -->", botMarker, shortSHA(sha), checkName)
}

// rebaseMarker tags a failed conflict-resolution comment for one commit, so
// the SHA is skipped on the next cycle.
func rebaseMarker(sha string) string {
	return fmt.Sprintf("%s rebase:%s -->", botMarker, shortSHA(sha))
}

// versionMarker is the plain bot marker, tagged with the agent version when
// known.
func versionMarker(version string) string {
	if version != "" {
		return fmt.Sprintf("%s v:%s -->", botMarker, shortSHA(version))
	}
	return botMarker + " -->"
}

// botComment returns the visible attribution footer with the invisible bot
// marker embedded.
func (a *Agent) botComment() string {
	return fmt.Sprintf("---\n*🤖 Generated by [oompa](https://github.com/qinqon/oompa). Use `/oompa` to talk with me.* %s", versionMarker(a.cfg.Version))
}
